/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_WASMContainer */

#ifndef _Included_com_example_WASMContainer
#define _Included_com_example_WASMContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_WASMContainer
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_WASMContainer_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_example_WASMContainer
 * Method:    handle
 * Signature: (Ljava/lang/String;Lcom/example/WASMContainer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_WASMContainer_handle
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
